[package]
name = "eserde"
edition.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true

[features]
default = ["derive"]
derive = ["serde/derive"]

[dependencies]
serde = { workspace = true }
eserde_derive = { path = "../eserde_derive" }
