name: "Fuzz all fuzz targets"

on:
  workflow_dispatch:
    inputs:
      duration_seconds:
        description: "The amount of time each target is fuzzed"
        required: true
        default: "10s"

env:
  CARGO_TERM_COLOR: always

jobs:
    fuzz:
      name: Fuzz
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: actions-rust-lang/setup-rust-toolchain@v1
          with:
            toolchain: nightly
        - name: Install cargo-fuzz
          run: cargo install --locked cargo-fuzz 
        - name: Fuzz all targets for ${{ github.event.inputs.duration_seconds }}
          run: for target in $(cargo fuzz list); do echo "=== Fuzzing target $target"; cargo +nightly fuzz run --release $target -- -max_total_time=${{ github.event.inputs.duration_seconds }}; echo "=== Done fuzzing target $target"; done
